46-881



# Merging Data -  pd.merge()function

Usually, the data come from multiple tables or files. So, before doing any data analysis, one needs to combine the files.

We will use the pandas library for that, so, first,

import the pandas library with the standard alias 'pd'

In [1]:
import pandas as pd

Let's create some tables:

In [2]:
df1 = pd.DataFrame({
    "state": ["A", "B", "C", "K"],
    "x": [1, 2, 4, 5]
})

print(df1)

df2 = pd.DataFrame({
    "state": ["A", "B", "C", "D"],
    "y": [10, 20, 40, 50]
})

print(df2)

  state  x
0     A  1
1     B  2
2     C  4
3     K  5
  state   y
0     A  10
1     B  20
2     C  40
3     D  50



#  Inner join

returns rows when there is a match in both tables.

`inner_join = pd.merge(df1, df2, on="state", how="inner")`

* **pd.merge()** is the function from the
pandas library that performs the merge operation.
* **df1** and **df2** are the two DataFrames we want to merge.
* **on="state"** specifies the column to use for joining the two DataFrames. The merge function will look for matching values in the "state" column in both df1 and df2.
* **how="inner"** specifies the type of join. An "inner" join returns only the rows where the join column ("state" in this case) has matching values in both DataFrames. Rows with no match in either DataFrame are excluded.

In [4]:
inner_join = pd.merge(df1, df2, on="state", how="inner")
print(inner_join)

  state  x   y
0     A  1  10
1     B  2  20
2     C  4  40

# Left join

returns all rows from the left table, even if there are no matches in the right table.

In [5]:
left_join = pd.merge(df1, df2, on="state", how="left")
print(left_join)

  state  x     y
0     A  1  10.0
1     B  2  20.0
2     C  4  40.0
3     K  5   NaN

# Right join
returns all rows from the right table, even if there are no matches in the left table.

In [6]:
right_join = pd.merge(df1, df2, on="state", how="right")
print(right_join)

  state    x   y
0     A  1.0  10
1     B  2.0  20
2     C  4.0  40
3     D  NaN  50

# Full join
returns all rows from both the tables and fill in NaN for missing matches on either side.

In [7]:
full_join = pd.merge(df1, df2, on="state", how="outer")
print(full_join)

  state    x     y
0     A  1.0  10.0
1     B  2.0  20.0
2     C  4.0  40.0
3     D  NaN  50.0
4     K  5.0   NaN

# What if column names don't match?

In [8]:
df3 = pd.DataFrame({
    "id": ["A", "B", "C", "D"],
    "y": [10, 20, 40, 50]
})

print(df3)
print(df1)

  id   y
0  A  10
1  B  20
2  C  40
3  D  50
  state  x
0     A  1
1     B  2
2     C  4
3     K  5

we can specify col names to perform the merge:

`merged_df = pd.merge(df1, df3, left_on="state", right_on="id", how="left")`

* pd.merge(df1, df3, ...) indicates that we are merging df1 and df3.
* left_on="state" tells pandas to use the "state" column from the left DataFrame (df1) as the merge key/variable.
* right_on="id" tells pandas to use the "id" column from the right DataFrame (df3) as the merge key/variable.
* how="left" specifies the type of join (you can use "inner", "right", or "outer" here as well, depending on your needs).

In [9]:
merged_df = pd.merge(df1, df3, left_on="state", right_on="id", how="left")
print(merged_df)

  state  x   id     y
0     A  1    A  10.0
1     B  2    B  20.0
2     C  4    C  40.0
3     K  5  NaN   NaN

In [10]:
merged_df13 = pd.merge(df1, df3, left_on="state", right_on="id", how="inner")
print(merged_df13)

  state  x id   y
0     A  1  A  10
1     B  2  B  20
2     C  4  C  40

#Join by multiple columns?

In [11]:
df5 = pd.DataFrame({
    "state": ["A", "B", "C", "K"],
    "year": [1990, 1991, 1992, 1994],
    "x": [1, 2, 3, 5]
})

df6 = pd.DataFrame({
    "state": ["A", "B", "C", "D"],
    "time": [1990, 1992, 1994, 1996],
    "y": [10, 20, 30, 40]
})

print(df5)

print(df6)

  state  year  x
0     A  1990  1
1     B  1991  2
2     C  1992  3
3     K  1994  5
  state  time   y
0     A  1990  10
1     B  1992  20
2     C  1994  30
3     D  1996  40

we woudl like to merge two tables using


 the state and the year from df5 and

 the state and the time from df6

` new_merge3 = pd.merge(df5, df6, left_on=["state", "year"], right_on=["state", "time"], how="left")`

* pd.merge(df5, df6, ...): We are merging df5 and df6.
left_on=["state", "year"]: This tells pandas to use a combination of the "state" and "year" columns from the left DataFrame (df5) as the keys for matching. Notice that we provide a list of column names.
* right_on=["state", "time"]: This tells pandas to use a combination of the "state" and "time" columns from the right DataFrame (df6) as the keys for matching. Again, we provide a list of column names.
* how="left": We're performing an left join here. You can change this to "inner", "right", or "outer" depending on your needs.

Before running the code, what will be the size of the resulting table?
Before running the code, what will be the size of the table if `inner` merge used instead?

In [12]:
new_merge3 = pd.merge(df5, df6, left_on=["state", "year"], right_on=["state", "time"], how="left")
print(new_merge3)

  state  year  x    time     y
0     A  1990  1  1990.0  10.0
1     B  1991  2     NaN   NaN
2     C  1992  3     NaN   NaN
3     K  1994  5     NaN   NaN

In [13]:
df5df6 = (
     pd.merge(df5, df6,
              left_on=["state", "year"],
              right_on=["state", "time"],
              how="left")
 )
print(df5df6)

  state  year  x    time     y
0     A  1990  1  1990.0  10.0
1     B  1991  2     NaN   NaN
2     C  1992  3     NaN   NaN
3     K  1994  5     NaN   NaN

# Where did the rows in your merged dataframe come from?

Adding **the indicator** parameter is very useful for understanding the results of your merge operation, as well as for filtering or analisys of the rows based on whether they had a match in one or both of the original DataFrames.

In [14]:
merged_with_indicator = pd.merge(df1, df2, on="state", how="outer", indicator=True)
print(merged_with_indicator)

  state    x     y      _merge
0     A  1.0  10.0        both
1     B  2.0  20.0        both
2     C  4.0  40.0        both
3     D  NaN  50.0  right_only
4     K  5.0   NaN   left_only

Then you can tabulate the _merge variable to quicky check the quality of your merge

In [15]:
merged_with_indicator['_merge'].value_counts()

_merge
both          3
left_only     1
right_only    1
Name: count, dtype: int64

# Appending data - pd.concat()

In [16]:
dfa1 = pd.DataFrame({
    "Age": [21, 15],
    "Name": ["John", "April"]
})

dfa2 = pd.DataFrame({
    "Name": ["Oscar", "Polly"],
    "Age": [45, 50]
})

print(dfa1)
print(dfa2)

   Age   Name
0   21   John
1   15  April
    Name  Age
0  Oscar   45
1  Polly   50

Here is how to use the pd.concat() function:

`dfa1_dfa2 = pd.concat([dfa1, dfa2], ignore_index=True)`

* pd.concat([dfa1, dfa2]) combines (concatenates) the two DataFrames vertically.
* `ignore_index=True` resets the index of the resulting DataFrame, which is often useful when appending.

In [17]:
dfa1_dfa2 = pd.concat([dfa1, dfa2], ignore_index=True)

print(dfa1_dfa2)

   Age   Name
0   21   John
1   15  April
2   45  Oscar
3   50  Polly

In [18]:
pd.concat([dfa1, dfa2])

   Age   Name
0   21   John
1   15  April
0   45  Oscar
1   50  Polly

What if variables are not the same in the two dataframes?
Not a probelm at all!

In [19]:
dfa3 = pd.DataFrame({
    "Name": ["James", "Emily"],
    "State": ["PA", "FL"]
})

print(dfa3)
print(dfa1)

    Name State
0  James    PA
1  Emily    FL
   Age   Name
0   21   John
1   15  April

In [20]:
dfa1_dfa3 = pd.concat([dfa1, dfa3], ignore_index=True)

print(dfa1_dfa3)

    Age   Name State
0  21.0   John   NaN
1  15.0  April   NaN
2   NaN  James    PA
3   NaN  Emily    FL

Note: there is no `indicator` option for the `pd.concat()` function.
If you want to keep track of the data source,
you need to manually add a variable (e.g., "source") to the original DataFrames BEFORE appending them.

In [21]:
dfa1['source'] = 'dfa1'
dfa3['source'] = 'dfa3'
print(dfa1)
print(dfa3)
dfa1_dfa3_ind = pd.concat(
    [dfa1, dfa3])

print(dfa1_dfa3_ind)

   Age   Name source
0   21   John   dfa1
1   15  April   dfa1
    Name State source
0  James    PA   dfa3
1  Emily    FL   dfa3
    Age   Name source State
0  21.0   John   dfa1   NaN
1  15.0  April   dfa1   NaN
0   NaN  James   dfa3    PA
1   NaN  Emily   dfa3    FL

# Pivoting - pd.melt()

In [23]:
data = pd.DataFrame({
    'country': ['Afghanistan', 'Brazil', 'China'],
    '1999': [19987071, 172006362, 1272915272],
    '2000': [20595360, 174504898, 1280428583]
})

print(data)

       country        1999        2000
0  Afghanistan    19987071    20595360
1       Brazil   172006362   174504898
2        China  1272915272  1280428583

In [24]:
df_long = pd.melt(data,
  # Columns to keep as identifier variables:
                  id_vars=['country'],
  # Columns to stack into one:
                   value_vars=['1999', '2000'],
  # Name for the stacked column:
                  var_name='year',
  # Name for the new column holding the unpivoted values
                  value_name='population')


print(df_long)

       country  year  population
0  Afghanistan  1999    19987071
1       Brazil  1999   172006362
2        China  1999  1272915272
3  Afghanistan  2000    20595360
4       Brazil  2000   174504898
5        China  2000  1280428583

*Explanation:*

* **`pd.melt(data, ...)`**: Applies the melt function to the "data" DataFrame.
* **`id_vars=['country']`**: Specifies the column(s) that should remain as identifier variables. In this case, 'country' remains a distinct column.
* **`value_vars=['1999', '2000']`**: Specifies the columns that you want to stack (unpivot or melt). The data from these columns will be stacked into a single column. **NOTE** pd.melt() automatically treats all columns not listed in **`id_vars`** as the columns to stack/unpivot - so you do not need to specify them!
* **`var_name='year'`**: This is the name you want for the new column that will contain the names of the columns that were unpivoted (i.e., '1999' and '2000').
* **`value_name='population'`**: This is the name you want for the new column that will contain the values from the unpivoted columns.


As a result we get a DataFrame with three columns:

`'country', 'year', and 'population', `

achieving the same transformation we did in R using the pivot_longer().

# Practice!
Use Labor Force Participation Rate.xlsx file.
  
To read an Excel file into a pandas DataFrame, you need to use the pd.read_excel() function.

Convert the data into long, tidy, data.
Call this data **`prate_long`**
What is the average participation rate in 1995?